### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by EamonHeffernan** [romainmenke/mdn-support-context#1]
This looks super helpful, it may not be a huge priority atm, but support for Firefox would be a super nice to have, even if it requires manual installation. The checker on Firefox doesn't show any incompatibilities so hopefully it would be a relatively simple port.

**Comment by romainmenke** [comment]
@EamonHeffernan I would need to look into this.

This demo, at this time, is also more a showcase of what "Baseline" could be.
So I am kind of hoping that "Baseline" improves enough so that this extension won't be needed anymore.

Adding support for Firefox would depend on the added maintenance cost of keeping it up to date.

**Comment by romainmenke** [comment]
This has been released for Firefox : https://addons.mozilla.org/en-US/firefox/addon/support-context/
